### ISSUE TITLE
Invalid datapack

### ISSUE THREAD

**Issue by TheoMarque** [Zefyro/Extended-Beacon-Range#1]
On start gives me an error:

[13:53:48 ERROR]: Parsing error loading custom advancement ebr:interact: Not a json array: {"block":{"blocks":["minecraft:beacon"]}} missed input: {"requirement":{"trigger":"minecraft:item_used_on_block","conditions":{"player":[{"condition":"minecraft:entity_scores","entity":"this","scores":{"ebr.Interact":1}}],"location":{"block":{"blocks":["minecraft:beacon"]}}}}}; Advancement criteria cannot be empty

But, other hand, works only for 1 level of beaon pyramid. next, 2, 3, 4 levels are ignored.

**Comment by Zefyro** [comment]
Which game version are you on and are you running any other game modifications like bukkit based server jars or mods?

**Comment by TheoMarque** [comment]
1.20.4, paper spigot (newest stable).
Mods only on client, withiut mods, behavior is the same. 
Some other datapacks used, but not modify beacons.  

Plugins - many, many, most own, but not touch beacons. 
Maybe a problem is with some detecting a pyramid? 
Tested on flat world - behavior is the same, just 50 blocks diameter and no more. 

<img width="175" alt="image" src="https://github.com/Zefyro/Extended-Beacon-Range/assets/19385639/cda15691-97ca-4bc7-8f8d-6d1c35d303a5">

<img width="1368" alt="image" src="https://github.com/Zefyro/Extended-Beacon-Range/assets/19385639/5964c197-870f-4d4a-b892-a197d7bd9729">

**Comment by Zefyro** [comment]
I'll be updating the pack to 1.20.4 but I won't promise it will work on any bukkit derived server software as those are notoriously breaking vanilla command parity.

for now I assume you are using the 1.18.x release of the datapack?

**Comment by TheoMarque** [comment]
Sure, tested commands, no breaking changes, but maybe other way to
implement is needed. Thanks for promise for updating to 1.20.4 :) If out, I
will test :)

sob., 13 sty 2024 o 21:05 Zefyro ***@***.***> napisał(a):
