### ISSUE TITLE
Blocks over beacon interrupt range

### ISSUE THREAD

**Issue by TheoMarque** [Zefyro/Extended-Beacon-Range#3]
Hi, It's me, again. Now I found an issue. 
If player build ANY block transparent for beacon beam - plugin stops working. 

Players sometimes use beacon coloring (by stained glass), or using non opaque block (like trapdoors, fences, soil) to avoid deadly hole to bedrock. 

Below is a list of transparent blocks that beam can pass trough:
https://minecraft.wiki/w/Opacity#Types_of_transparent_blocks

Please, update a your fancy datapack :)

**Comment by Zefyro** [comment]
You are right, that is an oversight on my part, I'll be making an update to fix this in the near future.
